---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: upgrade repository
    apt:
      state: latest
      upgrade: yes
    when: ansible_distribution == "Ubuntu"
    